/*
 * This source file was generated by the Gradle 'init' task
 */
package projet; // Le package 'projet' est ici correct pour Main.java
// Importations nécessaires pour les classes utilisées
import projet.controller.PersonalityTestController;
import projet.model.ResultStrategy;
import projet.model.SimpleCountStrategy;
import projet.model.WeightedStrategy;
import projet.view.ConsolePersonalityTestView;
import projet.view.PersonalityTestView;
/**
 * Classe main pour démarrer l'application.
 * Usage :
 *   java -cp target/classes app.Main          -> utilise la stratégie "simple"
 *   java -cp target/classes app.Main weighted -> utilise la stratégie "weighted"
 */
public class Main {
    public static void main(String[] args) {
        // Détermine la stratégie à utiliser en fonction de l'argument de ligne de commande
        // Si aucun argument ou un argument différent de "weighted" est fourni, utilise "simple".
        String strategyArg = (args != null && args.length > 0) ? args[0] : "simple";
        ResultStrategy strategy;
        if ("weighted".equalsIgnoreCase(strategyArg)) {
            strategy = new WeightedStrategy();
            System.out.println("Using WeightedStrategy"); // Guillemets droits
        } else {
            strategy = new SimpleCountStrategy();
            System.out.println("Using SimpleCountStrategy"); // **CORRECTION ICI : Guillemets droits**
        }
        // Instanciation de la vue (interface utilisateur, ici console)
        PersonalityTestView view = new ConsolePersonalityTestView();
        // Instanciation du contrôleur avec la vue et la stratégie choisie
        PersonalityTestController controller = new PersonalityTestController(view, strategy);
        // Initialisation des questions via le contrôleur
        controller.initQuestions();
        // Lancement du test de personnalité
        controller.runTest();
    }
}